#!/bin/bash
#rm $HOME/.zshrc
ln -sfvT $PWD/zshrc $HOME/.zshrc
ln -sfvT $PWD/oh-my-zsh $HOME/.oh-my-zsh
#rm $HOME/.gitconfig
ln -sfvT $PWD/gitconfig $HOME/.gitconfig
#rm $HOME/.latexmkrc
ln -sfvT $PWD/latexmkrc $HOME/.latexmkrc
#rm $HOME/.pentadactylrc
ln -sfvT $PWD/pentadactylrc $HOME/.pentadactylrc
#rm $HOME/.screenrc
ln -sfvT $PWD/screenrc $HOME/.screenrc
#rm $HOME/.conkyrc
ln -sfvT $PWD/conkyrc $HOME/.conkyrc
ln -sfvT $PWD/vim $HOME/.vim
#rm $HOME/.vimrc
ln -sfvT $PWD/vimrc $HOME/.vimrc
ln -sfvT $PWD/bin $HOME/bin
ln -sfvT $PWD/config $HOME/.config
ln -sfvT $PWD/htop $HOME/.htop
