#!/bin/zsh
BIN='gln'
OPTS='-sfvT'
FILES=(zshrc oh-my-zsh gitconfig latexmkrc pentadactylrc screenrc vim vimrc)

for f in $FILES; do
    $BIN $OPTS $PWD/$f $HOME/.$f
done

# special case for bin, does not get a dot
$BIN $OPTS $PWD/bin $HOME/bin

# copy stuff that needs to be copied, but is untracked by git
# due to submodule stuff
cp -v vlsd.zsh-theme oh-my-zsh/themes/
